export const FETCH_TASK_LIST = 'FETCH_TASK_LIST';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAILED = 'FETCH_TASK_LIST_FAILED';

export const SEARCH_TASK = 'SEARCH_TASK';
export const SEARCH_TASK_SUCCESS = 'SEARCH_TASK_SUCCESS';

export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const CREATE_NEW_TASK_SUCCESS = 'CREATE_NEW_TASK_SUCCESS';
export const CREATE_NEW_TASK_FAILED = 'CREATE_NEW_TASK_FAILED';

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';

export const SET_TASK_EDIT_DATA = 'SET_TASK_EDIT_DATA';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';